// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5163/' | (string & {});
};

export type AddBoxDto = {
    name: string;
    groupId?: null | string;
};

export type AddCardDto = {
    setCode: null | string;
    setNumber: null | string;
    name: null | string;
    condition: string;
    foilType?: string;
    stampType?: string;
    language?: string;
    isProxy?: boolean;
    isSigned?: boolean;
    isList?: boolean;
    alterArtist?: null | string;
    notes?: null | string;
    boxId?: null | string;
    acquiredDate?: null | string;
    purchasePrice?: null | number | string;
};

export type AddEntityDto = {
    name: string;
    type?: string;
    location?: null | string;
};

export type AddGroupDto = {
    name: string;
    description?: null | string;
    entityId?: null | string;
    parentGroupId?: null | string;
};

export type BoxDto = {
    id: string;
    name: string;
    groupId: null | string;
    cardCount: number | string;
};

export type BreadcrumbDto = {
    entityName: null | string;
    entityId: null | string;
    rootGroupName: null | string;
    rootGroupId: null | string;
    hasCollapsed: boolean;
    parentGroupName: null | string;
    parentGroupId: null | string;
    boxName: null | string;
    boxId: null | string;
};

export type CardDto = {
    id: string;
    name: null | string;
    setCode: null | string;
    setNumber: null | string;
    scryfallId: null | string;
    condition: string;
    foilType: string;
    stampType: string;
    language: string;
    isProxy: boolean;
    isSigned: boolean;
    isList: boolean;
    alterArtist: null | string;
    notes: null | string;
    boxId: null | string;
    tags: Array<string>;
};

export type GroupDto = {
    id: string;
    name: string;
    description: null | string;
    entityId: null | string;
    parentGroupId: null | string;
    childGroupNames: Array<string>;
    boxNames: Array<string>;
};

export type GroupedCardDto = {
    name: null | string;
    setCode: null | string;
    setNumber: null | string;
    scryfallId: null | string;
    condition: string;
    foilType: string;
    stampType: string;
    count: number | string;
    ids: Array<string>;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type UpdateBoxDto = {
    name: null | string;
    groupId: null | string;
};

export type UpdateCardDto = {
    setCode: null | string;
    setNumber: null | string;
    name: null | string;
    condition: null | string;
    foilType: null | string;
    stampType: null | string;
    language: null | string;
    isProxy: null | boolean;
    isSigned: null | boolean;
    isList: null | boolean;
    alterArtist: null | string;
    notes: null | string;
    boxId: null | string;
    acquiredDate: null | string;
    purchasePrice: null | number | string;
};

export type UpdateEntityDto = {
    name: null | string;
    type: null | string;
    location: null | string;
};

export type UpdateGroupDto = {
    name: null | string;
    description: null | string;
    entityId: null | string;
    parentGroupId: null | string;
};

export type GetApiBoxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/boxes';
};

export type GetApiBoxesResponses = {
    /**
     * OK
     */
    200: Array<BoxDto>;
};

export type GetApiBoxesResponse = GetApiBoxesResponses[keyof GetApiBoxesResponses];

export type PostApiBoxesData = {
    body: AddBoxDto;
    path?: never;
    query?: never;
    url: '/api/boxes';
};

export type PostApiBoxesResponses = {
    /**
     * Created
     */
    201: BoxDto;
};

export type PostApiBoxesResponse = PostApiBoxesResponses[keyof PostApiBoxesResponses];

export type DeleteApiBoxesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/boxes/{id}';
};

export type DeleteApiBoxesByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiBoxesByIdError = DeleteApiBoxesByIdErrors[keyof DeleteApiBoxesByIdErrors];

export type DeleteApiBoxesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiBoxesByIdResponse = DeleteApiBoxesByIdResponses[keyof DeleteApiBoxesByIdResponses];

export type GetApiBoxesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/boxes/{id}';
};

export type GetApiBoxesByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiBoxesByIdError = GetApiBoxesByIdErrors[keyof GetApiBoxesByIdErrors];

export type GetApiBoxesByIdResponses = {
    /**
     * OK
     */
    200: BoxDto;
};

export type GetApiBoxesByIdResponse = GetApiBoxesByIdResponses[keyof GetApiBoxesByIdResponses];

export type PutApiBoxesByIdData = {
    body: UpdateBoxDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/boxes/{id}';
};

export type PutApiBoxesByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiBoxesByIdError = PutApiBoxesByIdErrors[keyof PutApiBoxesByIdErrors];

export type PutApiBoxesByIdResponses = {
    /**
     * OK
     */
    200: BoxDto;
};

export type PutApiBoxesByIdResponse = PutApiBoxesByIdResponses[keyof PutApiBoxesByIdResponses];

export type GetApiBoxesByGroupByGroupIdData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/boxes/by-group/{groupId}';
};

export type GetApiBoxesByGroupByGroupIdResponses = {
    /**
     * OK
     */
    200: Array<BoxDto>;
};

export type GetApiBoxesByGroupByGroupIdResponse = GetApiBoxesByGroupByGroupIdResponses[keyof GetApiBoxesByGroupByGroupIdResponses];

export type GetApiBreadcrumbByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/breadcrumb/{id}';
};

export type GetApiBreadcrumbByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiBreadcrumbByIdError = GetApiBreadcrumbByIdErrors[keyof GetApiBreadcrumbByIdErrors];

export type GetApiBreadcrumbByIdResponses = {
    /**
     * OK
     */
    200: BreadcrumbDto;
};

export type GetApiBreadcrumbByIdResponse = GetApiBreadcrumbByIdResponses[keyof GetApiBreadcrumbByIdResponses];

export type GetApiCardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cards';
};

export type GetApiCardsResponses = {
    /**
     * OK
     */
    200: Array<CardDto>;
};

export type GetApiCardsResponse = GetApiCardsResponses[keyof GetApiCardsResponses];

export type PostApiCardsData = {
    body: AddCardDto;
    path?: never;
    query?: never;
    url: '/api/cards';
};

export type PostApiCardsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiCardsError = PostApiCardsErrors[keyof PostApiCardsErrors];

export type PostApiCardsResponses = {
    /**
     * Created
     */
    201: CardDto;
};

export type PostApiCardsResponse = PostApiCardsResponses[keyof PostApiCardsResponses];

export type DeleteApiCardsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cards/{id}';
};

export type DeleteApiCardsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiCardsByIdError = DeleteApiCardsByIdErrors[keyof DeleteApiCardsByIdErrors];

export type DeleteApiCardsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiCardsByIdResponse = DeleteApiCardsByIdResponses[keyof DeleteApiCardsByIdResponses];

export type GetApiCardsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cards/{id}';
};

export type GetApiCardsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiCardsByIdError = GetApiCardsByIdErrors[keyof GetApiCardsByIdErrors];

export type GetApiCardsByIdResponses = {
    /**
     * OK
     */
    200: CardDto;
};

export type GetApiCardsByIdResponse = GetApiCardsByIdResponses[keyof GetApiCardsByIdResponses];

export type PutApiCardsByIdData = {
    body: UpdateCardDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cards/{id}';
};

export type PutApiCardsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiCardsByIdError = PutApiCardsByIdErrors[keyof PutApiCardsByIdErrors];

export type PutApiCardsByIdResponses = {
    /**
     * OK
     */
    200: CardDto;
};

export type PutApiCardsByIdResponse = PutApiCardsByIdResponses[keyof PutApiCardsByIdResponses];

export type GetApiCardsByBoxByBoxIdData = {
    body?: never;
    path: {
        boxId: string;
    };
    query?: never;
    url: '/api/cards/by-box/{boxId}';
};

export type GetApiCardsByBoxByBoxIdResponses = {
    /**
     * OK
     */
    200: Array<CardDto>;
};

export type GetApiCardsByBoxByBoxIdResponse = GetApiCardsByBoxByBoxIdResponses[keyof GetApiCardsByBoxByBoxIdResponses];

export type GetApiCardsByBoxByBoxIdGroupedData = {
    body?: never;
    path: {
        boxId: string;
    };
    query?: never;
    url: '/api/cards/by-box/{boxId}/grouped';
};

export type GetApiCardsByBoxByBoxIdGroupedResponses = {
    /**
     * OK
     */
    200: Array<GroupedCardDto>;
};

export type GetApiCardsByBoxByBoxIdGroupedResponse = GetApiCardsByBoxByBoxIdGroupedResponses[keyof GetApiCardsByBoxByBoxIdGroupedResponses];

export type GetApiEntitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/entities';
};

export type GetApiEntitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiEntitiesData = {
    body: AddEntityDto;
    path?: never;
    query?: never;
    url: '/api/entities';
};

export type PostApiEntitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiEntitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/entities/{id}';
};

export type DeleteApiEntitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiEntitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/entities/{id}';
};

export type GetApiEntitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiEntitiesByIdData = {
    body: UpdateEntityDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/entities/{id}';
};

export type PutApiEntitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type GetApiGroupsResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetApiGroupsResponse = GetApiGroupsResponses[keyof GetApiGroupsResponses];

export type PostApiGroupsData = {
    body: AddGroupDto;
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type PostApiGroupsResponses = {
    /**
     * Created
     */
    201: GroupDto;
};

export type PostApiGroupsResponse = PostApiGroupsResponses[keyof PostApiGroupsResponses];

export type DeleteApiGroupsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type DeleteApiGroupsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiGroupsByIdError = DeleteApiGroupsByIdErrors[keyof DeleteApiGroupsByIdErrors];

export type DeleteApiGroupsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiGroupsByIdResponse = DeleteApiGroupsByIdResponses[keyof DeleteApiGroupsByIdResponses];

export type GetApiGroupsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetApiGroupsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiGroupsByIdError = GetApiGroupsByIdErrors[keyof GetApiGroupsByIdErrors];

export type GetApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type GetApiGroupsByIdResponse = GetApiGroupsByIdResponses[keyof GetApiGroupsByIdResponses];

export type PutApiGroupsByIdData = {
    body: UpdateGroupDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type PutApiGroupsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiGroupsByIdError = PutApiGroupsByIdErrors[keyof PutApiGroupsByIdErrors];

export type PutApiGroupsByIdResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type PutApiGroupsByIdResponse = PutApiGroupsByIdResponses[keyof PutApiGroupsByIdResponses];

export type GetApiGroupsByEntityByEntityIdData = {
    body?: never;
    path: {
        entityId: string;
    };
    query?: never;
    url: '/api/groups/by-entity/{entityId}';
};

export type GetApiGroupsByEntityByEntityIdResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetApiGroupsByEntityByEntityIdResponse = GetApiGroupsByEntityByEntityIdResponses[keyof GetApiGroupsByEntityByEntityIdResponses];

export type GetApiGroupsByParentByParentIdData = {
    body?: never;
    path: {
        parentId: string;
    };
    query?: never;
    url: '/api/groups/by-parent/{parentId}';
};

export type GetApiGroupsByParentByParentIdResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetApiGroupsByParentByParentIdResponse = GetApiGroupsByParentByParentIdResponses[keyof GetApiGroupsByParentByParentIdResponses];
