// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quartzwood.Server.Data;

#nullable disable

namespace Quartzwood.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009031602_AddCardIsList")]
    partial class AddCardIsList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Quartzwood.Server.Models.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.CardInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlterArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlterDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlterPhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoilType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProxy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NameSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("StampType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.CardTag", b =>
                {
                    b.Property<Guid>("CardInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("CardInstanceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CardTags");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Box", b =>
                {
                    b.HasOne("Quartzwood.Server.Models.Group", "Group")
                        .WithMany("Boxes")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.CardInstance", b =>
                {
                    b.HasOne("Quartzwood.Server.Models.Box", "Box")
                        .WithMany("Cards")
                        .HasForeignKey("BoxId");

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.CardTag", b =>
                {
                    b.HasOne("Quartzwood.Server.Models.CardInstance", "Card")
                        .WithMany("CardTags")
                        .HasForeignKey("CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quartzwood.Server.Models.Tag", "Tag")
                        .WithMany("CardTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Group", b =>
                {
                    b.HasOne("Quartzwood.Server.Models.Entity", "Entity")
                        .WithMany("Groups")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Quartzwood.Server.Models.Group", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Entity");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Box", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.CardInstance", b =>
                {
                    b.Navigation("CardTags");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Entity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Group", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("ChildGroups");
                });

            modelBuilder.Entity("Quartzwood.Server.Models.Tag", b =>
                {
                    b.Navigation("CardTags");
                });
#pragma warning restore 612, 618
        }
    }
}
